// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../core/index.js";
import * as errors from "../../../../errors/index.js";
import type * as FernSampleApi from "../../../index.js";

export class MovieDoesNotExistError extends errors.FernSampleApiError {
    constructor(body: FernSampleApi.MovieId, rawResponse?: core.RawResponse) {
        super({
            message: "MovieDoesNotExistError",
            statusCode: 404,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, MovieDoesNotExistError.prototype);
    }
}
