// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         orderId: 1000000
 *     }
 */
export interface DeleteOrderRequest {
    /** ID of the order that needs to be deleted */
    orderId: number;
}
