// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         orderId: 1000000
 *     }
 */
export interface GetOrderByIdRequest {
    /** ID of order that needs to be fetched */
    orderId: number;
}
