// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as FernPerstoreReleaseFlowApi from "../../../index.js";

export declare namespace StoreClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Access to Petstore orders
 */
export class StoreClient {
    protected readonly _options: StoreClient.Options;

    constructor(options: StoreClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Returns a map of status codes to quantities.
     *
     * @param {StoreClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.store.getInventory()
     */
    public getInventory(requestOptions?: StoreClient.RequestOptions): core.HttpResponsePromise<Record<string, number>> {
        return core.HttpResponsePromise.fromPromise(this.__getInventory(requestOptions));
    }

    private async __getInventory(
        requestOptions?: StoreClient.RequestOptions,
    ): Promise<core.WithRawResponse<Record<string, number>>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                api_key: requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernPerstoreReleaseFlowApiEnvironment.Default,
                "store/inventory",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Record<string, number>, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FernPerstoreReleaseFlowApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernPerstoreReleaseFlowApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernPerstoreReleaseFlowApiTimeoutError(
                    "Timeout exceeded when calling GET /store/inventory.",
                );
            case "unknown":
                throw new errors.FernPerstoreReleaseFlowApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Place a new order in the store.
     *
     * @param {FernPerstoreReleaseFlowApi.Order} request
     * @param {StoreClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernPerstoreReleaseFlowApi.BadRequestError}
     * @throws {@link FernPerstoreReleaseFlowApi.UnprocessableEntityError}
     *
     * @example
     *     await client.store.placeOrder({})
     */
    public placeOrder(
        request: FernPerstoreReleaseFlowApi.Order,
        requestOptions?: StoreClient.RequestOptions,
    ): core.HttpResponsePromise<FernPerstoreReleaseFlowApi.Order> {
        return core.HttpResponsePromise.fromPromise(this.__placeOrder(request, requestOptions));
    }

    private async __placeOrder(
        request: FernPerstoreReleaseFlowApi.Order,
        requestOptions?: StoreClient.RequestOptions,
    ): Promise<core.WithRawResponse<FernPerstoreReleaseFlowApi.Order>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernPerstoreReleaseFlowApiEnvironment.Default,
                "store/order",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as FernPerstoreReleaseFlowApi.Order, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new FernPerstoreReleaseFlowApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 422:
                    throw new FernPerstoreReleaseFlowApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernPerstoreReleaseFlowApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernPerstoreReleaseFlowApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernPerstoreReleaseFlowApiTimeoutError(
                    "Timeout exceeded when calling POST /store/order.",
                );
            case "unknown":
                throw new errors.FernPerstoreReleaseFlowApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
     *
     * @param {FernPerstoreReleaseFlowApi.GetOrderByIdRequest} request
     * @param {StoreClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernPerstoreReleaseFlowApi.BadRequestError}
     * @throws {@link FernPerstoreReleaseFlowApi.NotFoundError}
     *
     * @example
     *     await client.store.getOrderById({
     *         orderId: 1000000
     *     })
     */
    public getOrderById(
        request: FernPerstoreReleaseFlowApi.GetOrderByIdRequest,
        requestOptions?: StoreClient.RequestOptions,
    ): core.HttpResponsePromise<FernPerstoreReleaseFlowApi.Order> {
        return core.HttpResponsePromise.fromPromise(this.__getOrderById(request, requestOptions));
    }

    private async __getOrderById(
        request: FernPerstoreReleaseFlowApi.GetOrderByIdRequest,
        requestOptions?: StoreClient.RequestOptions,
    ): Promise<core.WithRawResponse<FernPerstoreReleaseFlowApi.Order>> {
        const { orderId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernPerstoreReleaseFlowApiEnvironment.Default,
                `store/order/${core.url.encodePathParam(orderId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as FernPerstoreReleaseFlowApi.Order, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new FernPerstoreReleaseFlowApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new FernPerstoreReleaseFlowApi.NotFoundError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernPerstoreReleaseFlowApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernPerstoreReleaseFlowApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernPerstoreReleaseFlowApiTimeoutError(
                    "Timeout exceeded when calling GET /store/order/{orderId}.",
                );
            case "unknown":
                throw new errors.FernPerstoreReleaseFlowApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
     *
     * @param {FernPerstoreReleaseFlowApi.DeleteOrderRequest} request
     * @param {StoreClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link FernPerstoreReleaseFlowApi.BadRequestError}
     * @throws {@link FernPerstoreReleaseFlowApi.NotFoundError}
     *
     * @example
     *     await client.store.deleteOrder({
     *         orderId: 1000000
     *     })
     */
    public deleteOrder(
        request: FernPerstoreReleaseFlowApi.DeleteOrderRequest,
        requestOptions?: StoreClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteOrder(request, requestOptions));
    }

    private async __deleteOrder(
        request: FernPerstoreReleaseFlowApi.DeleteOrderRequest,
        requestOptions?: StoreClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { orderId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FernPerstoreReleaseFlowApiEnvironment.Default,
                `store/order/${core.url.encodePathParam(orderId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new FernPerstoreReleaseFlowApi.BadRequestError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new FernPerstoreReleaseFlowApi.NotFoundError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.FernPerstoreReleaseFlowApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FernPerstoreReleaseFlowApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FernPerstoreReleaseFlowApiTimeoutError(
                    "Timeout exceeded when calling DELETE /store/order/{orderId}.",
                );
            case "unknown":
                throw new errors.FernPerstoreReleaseFlowApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
