// This file was auto-generated by Fern from our API Definition.

export class FernSampleApiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, FernSampleApiTimeoutError.prototype);
    }
}
