// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as PetStore from "../../../index.js";

export declare namespace UserClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations about user
 */
export class UserClient {
    protected readonly _options: UserClient.Options;

    constructor(options: UserClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * This can only be done by the logged in user.
     *
     * @param {PetStore.User} request
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.createUser({})
     */
    public createUser(
        request: PetStore.User,
        requestOptions?: UserClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.User> {
        return core.HttpResponsePromise.fromPromise(this.__createUser(request, requestOptions));
    }

    private async __createUser(
        request: PetStore.User,
        requestOptions?: UserClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.User>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                "user",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.User, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PetStoreError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling POST /user.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates list of users with given input array.
     *
     * @param {PetStore.User[]} request
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.createUsersWithListInput([{}])
     */
    public createUsersWithListInput(
        request: PetStore.User[],
        requestOptions?: UserClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.User> {
        return core.HttpResponsePromise.fromPromise(this.__createUsersWithListInput(request, requestOptions));
    }

    private async __createUsersWithListInput(
        request: PetStore.User[],
        requestOptions?: UserClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.User>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                "user/createWithList",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.User, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PetStoreError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling POST /user/createWithList.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Log into the system.
     *
     * @param {PetStore.LoginUserRequest} request
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     *
     * @example
     *     await client.user.loginUser()
     */
    public loginUser(
        request: PetStore.LoginUserRequest = {},
        requestOptions?: UserClient.RequestOptions,
    ): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__loginUser(request, requestOptions));
    }

    private async __loginUser(
        request: PetStore.LoginUserRequest = {},
        requestOptions?: UserClient.RequestOptions,
    ): Promise<core.WithRawResponse<string>> {
        const { username, password } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (username != null) {
            _queryParams.username = username;
        }

        if (password != null) {
            _queryParams.password = password;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                "user/login",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling GET /user/login.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Log user out of the system.
     *
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.user.logoutUser()
     */
    public logoutUser(requestOptions?: UserClient.RequestOptions): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__logoutUser(requestOptions));
    }

    private async __logoutUser(requestOptions?: UserClient.RequestOptions): Promise<core.WithRawResponse<void>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                "user/logout",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.PetStoreError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling GET /user/logout.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get user detail based on username.
     *
     * @param {PetStore.GetUserByNameRequest} request
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     * @throws {@link PetStore.NotFoundError}
     *
     * @example
     *     await client.user.getUserByName({
     *         username: "username"
     *     })
     */
    public getUserByName(
        request: PetStore.GetUserByNameRequest,
        requestOptions?: UserClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.User> {
        return core.HttpResponsePromise.fromPromise(this.__getUserByName(request, requestOptions));
    }

    private async __getUserByName(
        request: PetStore.GetUserByNameRequest,
        requestOptions?: UserClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.User>> {
        const { username } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                `user/${core.url.encodePathParam(username)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.User, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new PetStore.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling GET /user/{username}.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * This can only be done by the logged in user.
     *
     * @param {PetStore.UpdateUserRequest} request
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     * @throws {@link PetStore.NotFoundError}
     *
     * @example
     *     await client.user.updateUser({
     *         username: "username",
     *         body: {}
     *     })
     */
    public updateUser(
        request: PetStore.UpdateUserRequest,
        requestOptions?: UserClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__updateUser(request, requestOptions));
    }

    private async __updateUser(
        request: PetStore.UpdateUserRequest,
        requestOptions?: UserClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { username, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                `user/${core.url.encodePathParam(username)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new PetStore.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling PUT /user/{username}.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * This can only be done by the logged in user.
     *
     * @param {PetStore.DeleteUserRequest} request
     * @param {UserClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     * @throws {@link PetStore.NotFoundError}
     *
     * @example
     *     await client.user.deleteUser({
     *         username: "username"
     *     })
     */
    public deleteUser(
        request: PetStore.DeleteUserRequest,
        requestOptions?: UserClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteUser(request, requestOptions));
    }

    private async __deleteUser(
        request: PetStore.DeleteUserRequest,
        requestOptions?: UserClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { username } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ api_key: requestOptions?.apiKey ?? this._options?.apiKey }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                `user/${core.url.encodePathParam(username)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new PetStore.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling DELETE /user/{username}.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
