// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         username: "username"
 *     }
 */
export interface DeleteUserRequest {
    /** The name that needs to be deleted */
    username: string;
}
