// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         username: "username"
 *     }
 */
export interface GetUserByNameRequest {
    /** The name that needs to be fetched. Use user1 for testing */
    username: string;
}
