// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface LoginUserRequest {
    /** The user name for login */
    username?: string;
    /** The password for login in clear text */
    password?: string;
}
