// This file was auto-generated by Fern from our API Definition.

import type * as PetStore from "../../../../index.js";

/**
 * @example
 *     {
 *         username: "username",
 *         body: {}
 *     }
 */
export interface UpdateUserRequest {
    /** name that need to be deleted */
    username: string;
    body: PetStore.User;
}
