// This file was auto-generated by Fern from our API Definition.

export const FindPetsByStatusRequestStatus = {
    Available: "available",
    Pending: "pending",
    Sold: "sold",
} as const;
export type FindPetsByStatusRequestStatus =
    (typeof FindPetsByStatusRequestStatus)[keyof typeof FindPetsByStatusRequestStatus];
