// This file was auto-generated by Fern from our API Definition.

export const OauthScope = {
    /**
     * modify pets in your account */
    WritePets: "write:pets",
    /**
     * read your pets */
    ReadPets: "read:pets",
} as const;
export type OauthScope = (typeof OauthScope)[keyof typeof OauthScope];
