// This file was auto-generated by Fern from our API Definition.

export interface Order {
    id?: number;
    petId?: number;
    quantity?: number;
    shipDate?: string;
    /** Order Status */
    status?: Order.Status;
    complete?: boolean;
}

export namespace Order {
    /** Order Status */
    export const Status = {
        Placed: "placed",
        Approved: "approved",
        Delivered: "delivered",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
