// This file was auto-generated by Fern from our API Definition.

import type * as PetStore from "../index.js";

export interface Pet {
    id?: number;
    name: string;
    category?: PetStore.Category;
    photoUrls: string[];
    tags?: PetStore.Tag[];
    /** pet status in the store */
    status?: Pet.Status;
}

export namespace Pet {
    /** pet status in the store */
    export const Status = {
        Available: "available",
        Pending: "pending",
        Sold: "sold",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
