// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as PetStore from "../../../index.js";

export declare namespace PetClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Everything about your Pets
 */
export class PetClient {
    protected readonly _options: PetClient.Options;

    constructor(options: PetClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Add a new pet to the store.
     *
     * @param {PetStore.Pet} request
     * @param {PetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     * @throws {@link PetStore.UnprocessableEntityError}
     *
     * @example
     *     await client.pet.addPet({
     *         name: "doggie",
     *         photoUrls: ["photoUrls"]
     *     })
     */
    public addPet(
        request: PetStore.Pet,
        requestOptions?: PetClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.Pet> {
        return core.HttpResponsePromise.fromPromise(this.__addPet(request, requestOptions));
    }

    private async __addPet(
        request: PetStore.Pet,
        requestOptions?: PetClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.Pet>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                api_key: requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                "pet",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.Pet, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new PetStore.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling POST /pet.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Update an existing pet by Id.
     *
     * @param {PetStore.Pet} request
     * @param {PetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     * @throws {@link PetStore.NotFoundError}
     * @throws {@link PetStore.UnprocessableEntityError}
     *
     * @example
     *     await client.pet.updatePet({
     *         name: "doggie",
     *         photoUrls: ["photoUrls"]
     *     })
     */
    public updatePet(
        request: PetStore.Pet,
        requestOptions?: PetClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.Pet> {
        return core.HttpResponsePromise.fromPromise(this.__updatePet(request, requestOptions));
    }

    private async __updatePet(
        request: PetStore.Pet,
        requestOptions?: PetClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.Pet>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                api_key: requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                "pet",
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.Pet, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new PetStore.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new PetStore.UnprocessableEntityError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling PUT /pet.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Multiple status values can be provided with comma separated strings.
     *
     * @param {PetStore.FindPetsByStatusRequest} request
     * @param {PetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     *
     * @example
     *     await client.pet.findPetsByStatus({
     *         status: "available"
     *     })
     */
    public findPetsByStatus(
        request: PetStore.FindPetsByStatusRequest,
        requestOptions?: PetClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.Pet[]> {
        return core.HttpResponsePromise.fromPromise(this.__findPetsByStatus(request, requestOptions));
    }

    private async __findPetsByStatus(
        request: PetStore.FindPetsByStatusRequest,
        requestOptions?: PetClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.Pet[]>> {
        const { status } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.status = status;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                api_key: requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                "pet/findByStatus",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.Pet[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling GET /pet/findByStatus.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
     *
     * @param {PetStore.FindPetsByTagsRequest} request
     * @param {PetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     *
     * @example
     *     await client.pet.findPetsByTags()
     */
    public findPetsByTags(
        request: PetStore.FindPetsByTagsRequest = {},
        requestOptions?: PetClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.Pet[]> {
        return core.HttpResponsePromise.fromPromise(this.__findPetsByTags(request, requestOptions));
    }

    private async __findPetsByTags(
        request: PetStore.FindPetsByTagsRequest = {},
        requestOptions?: PetClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.Pet[]>> {
        const { tags } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (tags != null) {
            if (Array.isArray(tags)) {
                _queryParams.tags = tags.map((item) => item);
            } else {
                _queryParams.tags = tags;
            }
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                api_key: requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                "pet/findByTags",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.Pet[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling GET /pet/findByTags.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns a single pet.
     *
     * @param {PetStore.GetPetByIdRequest} request
     * @param {PetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     * @throws {@link PetStore.NotFoundError}
     *
     * @example
     *     await client.pet.getPetById({
     *         petId: 1000000
     *     })
     */
    public getPetById(
        request: PetStore.GetPetByIdRequest,
        requestOptions?: PetClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.Pet> {
        return core.HttpResponsePromise.fromPromise(this.__getPetById(request, requestOptions));
    }

    private async __getPetById(
        request: PetStore.GetPetByIdRequest,
        requestOptions?: PetClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.Pet>> {
        const { petId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                api_key: requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                `pet/${core.url.encodePathParam(petId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.Pet, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new PetStore.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling GET /pet/{petId}.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Updates a pet resource based on the form data.
     *
     * @param {PetStore.UpdatePetWithFormRequest} request
     * @param {PetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     *
     * @example
     *     await client.pet.updatePetWithForm({
     *         petId: 1000000
     *     })
     */
    public updatePetWithForm(
        request: PetStore.UpdatePetWithFormRequest,
        requestOptions?: PetClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.Pet> {
        return core.HttpResponsePromise.fromPromise(this.__updatePetWithForm(request, requestOptions));
    }

    private async __updatePetWithForm(
        request: PetStore.UpdatePetWithFormRequest,
        requestOptions?: PetClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.Pet>> {
        const { petId, name, status } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (name != null) {
            _queryParams.name = name;
        }

        if (status != null) {
            _queryParams.status = status;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                api_key: requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                `pet/${core.url.encodePathParam(petId)}`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.Pet, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling POST /pet/{petId}.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a pet.
     *
     * @param {PetStore.DeletePetRequest} request
     * @param {PetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     *
     * @example
     *     await client.pet.deletePet({
     *         petId: 1000000
     *     })
     */
    public deletePet(
        request: PetStore.DeletePetRequest,
        requestOptions?: PetClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deletePet(request, requestOptions));
    }

    private async __deletePet(
        request: PetStore.DeletePetRequest,
        requestOptions?: PetClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { petId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                api_key: requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                `pet/${core.url.encodePathParam(petId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling DELETE /pet/{petId}.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Upload image of the pet.
     *
     * @param {core.file.Uploadable} uploadable
     * @param {number} petId
     * @param {PetStore.UploadFileRequest} request
     * @param {PetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link PetStore.BadRequestError}
     * @throws {@link PetStore.NotFoundError}
     */
    public uploadFile(
        uploadable: core.file.Uploadable,
        petId: number,
        request: PetStore.UploadFileRequest,
        requestOptions?: PetClient.RequestOptions,
    ): core.HttpResponsePromise<PetStore.ApiResponse> {
        return core.HttpResponsePromise.fromPromise(this.__uploadFile(uploadable, petId, request, requestOptions));
    }

    private async __uploadFile(
        uploadable: core.file.Uploadable,
        petId: number,
        request: PetStore.UploadFileRequest,
        requestOptions?: PetClient.RequestOptions,
    ): Promise<core.WithRawResponse<PetStore.ApiResponse>> {
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (request.additionalMetadata != null) {
            _queryParams.additionalMetadata = request.additionalMetadata;
        }

        const _binaryUploadRequest = await core.file.toBinaryUploadRequest(uploadable);
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                api_key: requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            _binaryUploadRequest.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PetStoreEnvironment.Default,
                `pet/${core.url.encodePathParam(petId)}/uploadImage`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/octet-stream",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "bytes",
            duplex: "half",
            body: _binaryUploadRequest.body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as PetStore.ApiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new PetStore.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new PetStore.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PetStoreError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PetStoreError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PetStoreTimeoutError("Timeout exceeded when calling POST /pet/{petId}/uploadImage.");
            case "unknown":
                throw new errors.PetStoreError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
