// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         petId: 1000000
 *     }
 */
export interface DeletePetRequest {
    /** Pet id to delete */
    petId: number;
}
