// This file was auto-generated by Fern from our API Definition.

import type * as FernPerstoreReleaseFlowApi from "../../../../index.js";

/**
 * @example
 *     {
 *         status: "available"
 *     }
 */
export interface FindPetsByStatusRequest {
    /** Status values that need to be considered for filter */
    status: FernPerstoreReleaseFlowApi.FindPetsByStatusRequestStatus;
}
