// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         petId: 1000000
 *     }
 */
export interface GetPetByIdRequest {
    /** ID of pet to return */
    petId: number;
}
