// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         petId: 1000000
 *     }
 */
export interface UpdatePetWithFormRequest {
    /** ID of pet that needs to be updated */
    petId: number;
    /** Name of pet that needs to be updated */
    name?: string;
    /** Status of pet that needs to be updated */
    status?: string;
}
