// This file was auto-generated by Fern from our API Definition.

import type * as FernSampleApi from "../../../index.js";

export interface Movie {
    id: FernSampleApi.MovieId;
    title: string;
    /** The rating scale out of ten stars */
    rating: number;
}
