// This file was auto-generated by Fern from our API Definition.

import * as FernPerstoreReleaseFlowApi from "../../src/api/index";
import { FernPerstoreReleaseFlowApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PetClient", () => {
    test("addPet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "doggie", photoUrls: ["photoUrls"] };
        const rawResponseBody = {
            id: 10,
            name: "doggie",
            category: { id: 1, name: "Dogs" },
            photoUrls: ["photoUrls"],
            tags: [{ id: 1000000, name: "name" }],
            status: "available",
        };
        server
            .mockEndpoint()
            .post("/pet")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pet.addPet({
            name: "doggie",
            photoUrls: ["photoUrls"],
        });
        expect(response).toEqual({
            id: 10,
            name: "doggie",
            category: {
                id: 1,
                name: "Dogs",
            },
            photoUrls: ["photoUrls"],
            tags: [
                {
                    id: 1000000,
                    name: "name",
                },
            ],
            status: "available",
        });
    });

    test("addPet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", photoUrls: ["photoUrls", "photoUrls"] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/pet")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pet.addPet({
                name: "name",
                photoUrls: ["photoUrls", "photoUrls"],
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });

    test("addPet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", photoUrls: ["photoUrls", "photoUrls"] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/pet")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pet.addPet({
                name: "name",
                photoUrls: ["photoUrls", "photoUrls"],
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.UnprocessableEntityError);
    });

    test("updatePet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "doggie", photoUrls: ["photoUrls"] };
        const rawResponseBody = {
            id: 10,
            name: "doggie",
            category: { id: 1, name: "Dogs" },
            photoUrls: ["photoUrls"],
            tags: [{ id: 1000000, name: "name" }],
            status: "available",
        };
        server
            .mockEndpoint()
            .put("/pet")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pet.updatePet({
            name: "doggie",
            photoUrls: ["photoUrls"],
        });
        expect(response).toEqual({
            id: 10,
            name: "doggie",
            category: {
                id: 1,
                name: "Dogs",
            },
            photoUrls: ["photoUrls"],
            tags: [
                {
                    id: 1000000,
                    name: "name",
                },
            ],
            status: "available",
        });
    });

    test("updatePet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", photoUrls: ["photoUrls", "photoUrls"] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/pet")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pet.updatePet({
                name: "name",
                photoUrls: ["photoUrls", "photoUrls"],
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });

    test("updatePet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", photoUrls: ["photoUrls", "photoUrls"] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/pet")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pet.updatePet({
                name: "name",
                photoUrls: ["photoUrls", "photoUrls"],
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.NotFoundError);
    });

    test("updatePet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { name: "name", photoUrls: ["photoUrls", "photoUrls"] };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/pet")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pet.updatePet({
                name: "name",
                photoUrls: ["photoUrls", "photoUrls"],
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.UnprocessableEntityError);
    });

    test("findPetsByStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = [
            {
                id: 10,
                name: "doggie",
                category: { id: 1, name: "Dogs" },
                photoUrls: ["photoUrls"],
                tags: [{}],
                status: "available",
            },
        ];
        server.mockEndpoint().get("/pet/findByStatus").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.pet.findPetsByStatus({
            status: "available",
        });
        expect(response).toEqual([
            {
                id: 10,
                name: "doggie",
                category: {
                    id: 1,
                    name: "Dogs",
                },
                photoUrls: ["photoUrls"],
                tags: [{}],
                status: "available",
            },
        ]);
    });

    test("findPetsByStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/pet/findByStatus").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.pet.findPetsByStatus({
                status: "available",
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });

    test("findPetsByTags (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = [
            {
                id: 1000000,
                name: "name",
                category: { id: 1000000, name: "name" },
                photoUrls: ["photoUrls", "photoUrls"],
                tags: [
                    { id: 1000000, name: "name" },
                    { id: 1000000, name: "name" },
                ],
                status: "available",
            },
            {
                id: 1000000,
                name: "name",
                category: { id: 1000000, name: "name" },
                photoUrls: ["photoUrls", "photoUrls"],
                tags: [
                    { id: 1000000, name: "name" },
                    { id: 1000000, name: "name" },
                ],
                status: "available",
            },
        ];
        server.mockEndpoint().get("/pet/findByTags").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.pet.findPetsByTags();
        expect(response).toEqual([
            {
                id: 1000000,
                name: "name",
                category: {
                    id: 1000000,
                    name: "name",
                },
                photoUrls: ["photoUrls", "photoUrls"],
                tags: [
                    {
                        id: 1000000,
                        name: "name",
                    },
                    {
                        id: 1000000,
                        name: "name",
                    },
                ],
                status: "available",
            },
            {
                id: 1000000,
                name: "name",
                category: {
                    id: 1000000,
                    name: "name",
                },
                photoUrls: ["photoUrls", "photoUrls"],
                tags: [
                    {
                        id: 1000000,
                        name: "name",
                    },
                    {
                        id: 1000000,
                        name: "name",
                    },
                ],
                status: "available",
            },
        ]);
    });

    test("findPetsByTags (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/pet/findByTags").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.pet.findPetsByTags();
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });

    test("getPetById (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: 10,
            name: "doggie",
            category: { id: 1, name: "Dogs" },
            photoUrls: ["photoUrls"],
            tags: [{ id: 1000000, name: "name" }],
            status: "available",
        };
        server.mockEndpoint().get("/pet/1000000").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.pet.getPetById({
            petId: 1000000,
        });
        expect(response).toEqual({
            id: 10,
            name: "doggie",
            category: {
                id: 1,
                name: "Dogs",
            },
            photoUrls: ["photoUrls"],
            tags: [
                {
                    id: 1000000,
                    name: "name",
                },
            ],
            status: "available",
        });
    });

    test("getPetById (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/pet/1000000").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.pet.getPetById({
                petId: 1000000,
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });

    test("getPetById (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/pet/1000000").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.pet.getPetById({
                petId: 1000000,
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.NotFoundError);
    });

    test("updatePetWithForm (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: 10,
            name: "doggie",
            category: { id: 1, name: "Dogs" },
            photoUrls: ["photoUrls"],
            tags: [{ id: 1000000, name: "name" }],
            status: "available",
        };
        server.mockEndpoint().post("/pet/1000000").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.pet.updatePetWithForm({
            petId: 1000000,
        });
        expect(response).toEqual({
            id: 10,
            name: "doggie",
            category: {
                id: 1,
                name: "Dogs",
            },
            photoUrls: ["photoUrls"],
            tags: [
                {
                    id: 1000000,
                    name: "name",
                },
            ],
            status: "available",
        });
    });

    test("updatePetWithForm (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().post("/pet/1000000").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.pet.updatePetWithForm({
                petId: 1000000,
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });

    test("deletePet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        server.mockEndpoint().delete("/pet/1000000").respondWith().statusCode(200).build();

        const response = await client.pet.deletePet({
            petId: 1000000,
        });
        expect(response).toEqual(undefined);
    });

    test("deletePet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/pet/1000000").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.pet.deletePet({
                petId: 1000000,
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });
});
