// This file was auto-generated by Fern from our API Definition.

import * as FernPerstoreReleaseFlowApi from "../../src/api/index";
import { FernPerstoreReleaseFlowApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("StoreClient", () => {
    test("getInventory", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: 1 };
        server.mockEndpoint().get("/store/inventory").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.store.getInventory();
        expect(response).toEqual({
            key: 1,
        });
    });

    test("placeOrder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: 10,
            petId: 198772,
            quantity: 7,
            shipDate: "2024-01-15T09:30:00Z",
            status: "placed",
            complete: true,
        };
        server
            .mockEndpoint()
            .post("/store/order")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.store.placeOrder({});
        expect(response).toEqual({
            id: 10,
            petId: 198772,
            quantity: 7,
            shipDate: "2024-01-15T09:30:00Z",
            status: "placed",
            complete: true,
        });
    });

    test("placeOrder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/store/order")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.store.placeOrder({});
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });

    test("placeOrder (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/store/order")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.store.placeOrder({});
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.UnprocessableEntityError);
    });

    test("getOrderById (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: 10,
            petId: 198772,
            quantity: 7,
            shipDate: "2024-01-15T09:30:00Z",
            status: "placed",
            complete: true,
        };
        server
            .mockEndpoint()
            .get("/store/order/1000000")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.store.getOrderById({
            orderId: 1000000,
        });
        expect(response).toEqual({
            id: 10,
            petId: 198772,
            quantity: 7,
            shipDate: "2024-01-15T09:30:00Z",
            status: "placed",
            complete: true,
        });
    });

    test("getOrderById (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/store/order/1000000")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.store.getOrderById({
                orderId: 1000000,
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });

    test("getOrderById (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/store/order/1000000")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.store.getOrderById({
                orderId: 1000000,
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.NotFoundError);
    });

    test("deleteOrder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        server.mockEndpoint().delete("/store/order/1000000").respondWith().statusCode(200).build();

        const response = await client.store.deleteOrder({
            orderId: 1000000,
        });
        expect(response).toEqual(undefined);
    });

    test("deleteOrder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/store/order/1000000")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.store.deleteOrder({
                orderId: 1000000,
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.BadRequestError);
    });

    test("deleteOrder (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new FernPerstoreReleaseFlowApiClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/store/order/1000000")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.store.deleteOrder({
                orderId: 1000000,
            });
        }).rejects.toThrow(FernPerstoreReleaseFlowApi.NotFoundError);
    });
});
