// This file was auto-generated by Fern from our API Definition.

import * as PetStore from "../../src/api/index";
import { PetStoreClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UserClient", () => {
    test("createUser", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: 10,
            username: "theUser",
            firstName: "John",
            lastName: "James",
            email: "john@email.com",
            password: "12345",
            phone: "12345",
            userStatus: 1,
        };
        server
            .mockEndpoint()
            .post("/user")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.user.createUser({});
        expect(response).toEqual({
            id: 10,
            username: "theUser",
            firstName: "John",
            lastName: "James",
            email: "john@email.com",
            password: "12345",
            phone: "12345",
            userStatus: 1,
        });
    });

    test("createUsersWithListInput", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = [{}];
        const rawResponseBody = {
            id: 10,
            username: "theUser",
            firstName: "John",
            lastName: "James",
            email: "john@email.com",
            password: "12345",
            phone: "12345",
            userStatus: 1,
        };
        server
            .mockEndpoint()
            .post("/user/createWithList")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.user.createUsersWithListInput([{}]);
        expect(response).toEqual({
            id: 10,
            username: "theUser",
            firstName: "John",
            lastName: "James",
            email: "john@email.com",
            password: "12345",
            phone: "12345",
            userStatus: 1,
        });
    });

    test("loginUser (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = "string";
        server.mockEndpoint().get("/user/login").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.user.loginUser();
        expect(response).toEqual("string");
    });

    test("loginUser (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/user/login").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.user.loginUser();
        }).rejects.toThrow(PetStore.BadRequestError);
    });

    test("logoutUser", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        server.mockEndpoint().get("/user/logout").respondWith().statusCode(200).build();

        const response = await client.user.logoutUser();
        expect(response).toEqual(undefined);
    });

    test("getUserByName (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: 10,
            username: "theUser",
            firstName: "John",
            lastName: "James",
            email: "john@email.com",
            password: "12345",
            phone: "12345",
            userStatus: 1,
        };
        server.mockEndpoint().get("/user/username").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.user.getUserByName({
            username: "username",
        });
        expect(response).toEqual({
            id: 10,
            username: "theUser",
            firstName: "John",
            lastName: "James",
            email: "john@email.com",
            password: "12345",
            phone: "12345",
            userStatus: 1,
        });
    });

    test("getUserByName (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/user/username").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.user.getUserByName({
                username: "username",
            });
        }).rejects.toThrow(PetStore.BadRequestError);
    });

    test("getUserByName (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/user/username").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.user.getUserByName({
                username: "username",
            });
        }).rejects.toThrow(PetStore.NotFoundError);
    });

    test("updateUser (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};

        server.mockEndpoint().put("/user/username").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.user.updateUser({
            username: "username",
            body: {},
        });
        expect(response).toEqual(undefined);
    });

    test("updateUser (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/user/username")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.user.updateUser({
                username: "username",
                body: {},
            });
        }).rejects.toThrow(PetStore.BadRequestError);
    });

    test("updateUser (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .put("/user/username")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.user.updateUser({
                username: "username",
                body: {},
            });
        }).rejects.toThrow(PetStore.NotFoundError);
    });

    test("deleteUser (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        server.mockEndpoint().delete("/user/username").respondWith().statusCode(200).build();

        const response = await client.user.deleteUser({
            username: "username",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteUser (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/user/username").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.user.deleteUser({
                username: "username",
            });
        }).rejects.toThrow(PetStore.BadRequestError);
    });

    test("deleteUser (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PetStoreClient({
            maxRetries: 0,
            token: "test",
            apiKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/user/username").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.user.deleteUser({
                username: "username",
            });
        }).rejects.toThrow(PetStore.NotFoundError);
    });
});
