// This file was auto-generated by Fern from our API Definition.

import { ImdbClient } from "./api/resources/imdb/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptions } from "./BaseClient.js";

export declare namespace FernReleaseFlowTestClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FernReleaseFlowTestClient {
    protected readonly _options: FernReleaseFlowTestClient.Options;
    protected _imdb: ImdbClient | undefined;

    constructor(options: FernReleaseFlowTestClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get imdb(): ImdbClient {
        return (this._imdb ??= new ImdbClient(this._options));
    }
}
