// This file was auto-generated by Fern from our API Definition.

import { PetClient } from "./api/resources/pet/client/Client.js";
import { StoreClient } from "./api/resources/store/client/Client.js";
import { UserClient } from "./api/resources/user/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptions } from "./BaseClient.js";

export declare namespace PetStoreClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PetStoreClient {
    protected readonly _options: PetStoreClient.Options;
    protected _pet: PetClient | undefined;
    protected _store: StoreClient | undefined;
    protected _user: UserClient | undefined;

    constructor(options: PetStoreClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get pet(): PetClient {
        return (this._pet ??= new PetClient(this._options));
    }

    public get store(): StoreClient {
        return (this._store ??= new StoreClient(this._options));
    }

    public get user(): UserClient {
        return (this._user ??= new UserClient(this._options));
    }
}
