// This file was auto-generated by Fern from our API Definition.

export const FernPerstoreReleaseFlowApiEnvironment = {
    Default: "/api/v3",
} as const;

export type FernPerstoreReleaseFlowApiEnvironment = typeof FernPerstoreReleaseFlowApiEnvironment.Default;
