// This file was auto-generated by Fern from our API Definition.

export const PetStoreEnvironment = {
    Default: "/api/v3",
} as const;

export type PetStoreEnvironment = typeof PetStoreEnvironment.Default;
